### ISSUE TITLE
Loading items...

### ISSUE THREAD

**Issue by WickedVisage** [steamcalculator/steamcalculator#3]
They never load for me.
https://steamcalculator.com/id/theonlywickedvisage

**Comment by spezifanta** [comment]
Thanks for reporting!

Yes, if an account has a few thousand games, steamcalculator.com will simply run in a timeout and crash.
We are working on a solution.

**Comment by d1337tion** [comment]
You mean just a couple hundred games? Cause it does not even take 1k to have it timeout; I'm under 800.

https://steamcalculator.com/id/d1337tion

**Comment by spezifanta** [comment]
Oh, this is not good. Yes, you are absolutely right, that is a serious bug. Thanks for pointing that out!

We managed to narrow down the problem. Has to due to lazy loading the app prices, unfortunately, it's not as easy to fix. We might have a workaround. I'll keep you updated.

**Comment by spezifanta** [comment]
Calculations are now much faster, so there should be fewer timeouts.

@WickedVisage, your account can now be [calculated](https://steamcalculator.com/id/theonlywickedvisage).

As for @d1337tion, Steam lists your account with zero games for the moment. We don't know why. Have a look yourself: https://steamcommunity.com/id/d1337tion/games/?tab=all

Again, thanks for reporting this issue.

**Comment by d1337tion** [comment]
I have no issues seeing my games tab, and my inventory can be calculated now.

https://steamcalculator.com/id/d1337tion

**Comment by spezifanta** [comment]
:shipit:

Well, that is good news.
Gonna close the issue then. Thanks.

**Comment by WickedVisage** [comment]
Steam (yesterday) just made everyone's gaming library hidden by default (this wasn't in their blog post).
